### ISSUE TITLE
Create Epic Read.me

### ISSUE THREAD

**Issue by louisblythe** [elevate360/Pacific#1]
Make a great read me file for the theme.

**Comment by louisblythe** [comment]
# Pacific WordPress Theme

The only corporate or businesses theme you will ever need to totally eclipse the competition.

# Getting Started

When you are ready to set this theme up follow the standard set up process so that you are all good. Simon to add more and very detailed set up breakdown.

# Prerequisites

What things you need to install the software and how to install them

# Give examples

Installing

A step by step series of examples that tell you have to get a development env running

Say what the step will be

Give the example
And repeat

until finished
End with an example of getting some data out of the system or using it for a little demo

Running the tests

Explain how to run the automated tests for this system

Break down into end to end tests

Explain what these tests test and why

Give an example
And coding style tests

Explain what these tests test and why

Give an example
Deployment

Add additional notes about how to deploy this on a live system

# Built With

WordPress
Cider
Elevate Portfolio Plugin
Elevate Testimonial Plugin
Elevate Services Plugin

Please read CONTRIBUTING.md for details on our code of conduct, and the process for submitting pull requests to us.

# Versioning

We use SemVer for versioning. For the versions available, see the tags on this repository.

# Authors

Simon
Louis
Harry
Christof
Satoko

See also the list of contributors who participated in this project.

License

This project is licensed under the MIT License - see the LICENSE.md file for details

Acknowledgments

Hat tip to anyone who's code was used
Inspiration
etc

**Comment by simonrcodrington** [comment]
Will be addressed and made fancy by launch at v1.0.0
